version: '3'
services:
  app:
    restart: unless-stopped
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    volumes:
      - .:/app
    networks:
      - app-network
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
 db: