version: '3'

services:
    application:
        container_name: fileserver
        restart: always
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/app